# Workflow name that appears in GitHub Actions UI
name: Deploy to Hostinger

# Define when this workflow will run
on:
  push:
    branches: [ master ]  # Trigger on pushes to master branch
  workflow_dispatch:      # Allow manual triggering from GitHub UI

# Jobs define the actual work to be performed
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Clone your repository code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Step 4: Build React application
      - name: Build project
        run: npm run build
        env:
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
      
      # Step 5: Create .htaccess for SPA routing in public_html
      - name: Create .htaccess file
        run: |
          cat > ./dist/.htaccess << 'EOL'
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-l
            RewriteRule . /index.html [L]
          </IfModule>
          EOL
      
      # Step 6: List files to be uploaded
      - name: Show files to be uploaded
        run: |
          echo "Files to be deployed:"
          find ./dist -type f | sort
          du -sh ./dist
      
      # Step 7: Use a reliable FTP deployment method (basic-ftp)
      - name: Deploy via FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.CLOUDHOST_SERVER }}
          user: ${{ secrets.CLOUDHOST_USERNAME }}
          password: ${{ secrets.CLOUDHOST_PASSWORD }}
          localDir: "dist"
          remoteDir: "public_html"
          options: "--delete --transfer-all"
