name: Deploy to Hostinger

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        env:
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
      
      - name: Install FTP client
        run: sudo apt-get update && sudo apt-get install -y ncftp
      
      - name: Deploy to Hostinger
        env:
          FTP_SERVER: ${{ secrets.CLOUDHOST_SERVER }}
          FTP_USERNAME: ${{ secrets.CLOUDHOST_USERNAME }}
          FTP_PASSWORD: ${{ secrets.CLOUDHOST_PASSWORD }}
        run: |
          # Create a temporary script file
          cat > ./ftp-script.txt << EOL
          open \$FTP_SERVER
          user \$FTP_USERNAME \$FTP_PASSWORD
          set confirm off
          clear
          cd /public_html
          lcd ./dist
          binary
          prompt off
          mput *
          mput -r *
          quit
          EOL
          
          # Replace variables in the script
          sed -i "s|\\\$FTP_SERVER|$FTP_SERVER|g" ./ftp-script.txt
          sed -i "s|\\\$FTP_USERNAME|$FTP_USERNAME|g" ./ftp-script.txt
          sed -i "s|\\\$FTP_PASSWORD|$FTP_PASSWORD|g" ./ftp-script.txt
          
          # Run the script
          ncftp -f ./ftp-script.txt
          
          echo "FTP upload completed"
