# Workflow name that appears in GitHub Actions UI
name: Deploy to Hostinger

# Define when this workflow will run
on:
  push:
    branches: [ master ]  # Trigger on pushes to master branch
  workflow_dispatch:      # Allow manual triggering from GitHub UI

# Jobs define the actual work to be performed
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Clone your repository code
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          ref: master
      
      # Step 2: Display what code is being deployed
      - name: Show latest commit info
        run: |
          echo "Deploying commit:"
          git log -1 --pretty=format:'%h - %s (%cr) by %cn'
      
      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Step 5: Build your React app for production
      - name: Build project
        run: npm run build
        env:
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
      
      # Step 6: Verify build output
      - name: List built files
        run: |
          echo "Files that will be deployed:"
          ls -la dist/
          du -sh dist/
      
      # Step 7: Install and use lftp for more reliable deployment
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
      
      # Step 8: Deploy using lftp (similar to manual FTP)
      - name: Deploy using lftp
        run: |
          lftp -c "
          set ftp:ssl-allow no;
          open ${{ secrets.CLOUDHOST_SERVER }};
          user ${{ secrets.CLOUDHOST_USERNAME }} ${{ secrets.CLOUDHOST_PASSWORD }};
          mirror -R ./dist/ /public_html/ --parallel=5 --verbose;
          bye
          "
      
      # Step 9: Verify deployment
      - name: Deployment completion
        run: |
          echo "Deployment completed at $(date)"
          echo "NOTE: Check your website to verify the changes are visible"
