name: Deploy to Hostinger

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        env:
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
      
      - name: Debug - List build files
        run: ls -la dist/
      
      - name: Basic FTP Upload
        run: |
          # Install curl
          sudo apt-get update
          sudo apt-get install -y curl
          
          # Create a simple script to upload each file using curl
          cd dist
          find . -type f -print0 | while IFS= read -r -d '' file; do
            echo "Uploading $file..."
            # Create directory if needed
            dirname=$(dirname "$file")
            if [ "$dirname" != "." ]; then
              curl -s --ftp-create-dirs -u "${{ secrets.CLOUDHOST_USERNAME }}:${{ secrets.CLOUDHOST_PASSWORD }}" "ftp://${{ secrets.CLOUDHOST_SERVER }}/public_html/${dirname:2}/" || true
            fi
            # Upload file
            curl -T "$file" -u "${{ secrets.CLOUDHOST_USERNAME }}:${{ secrets.CLOUDHOST_PASSWORD }}" "ftp://${{ secrets.CLOUDHOST_SERVER }}/public_html/${file:2}" --ftp-pasv
            echo "$file uploaded"
          done
          
          echo "All files uploaded"
